# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-15 20:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('nickname', models.CharField(max_length=10)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
