# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-22 19:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_app',
            name='id',
        ),
        migrations.AddField(
            model_name='user_app',
            name='email',
            field=models.CharField(default=datetime.datetime(2017, 1, 22, 19, 5, 10, 909000), max_length=30, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
