# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-27 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_auto_20170122_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='test',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
